version: "3.1"  # optional since v1.27.0
services:
  node:
    build: .
    container_name: test
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/test
    depends_on:
      - mongo
    restart: always
#    networks:
#      - test-app
    deploy:
      replicas: 3
#networks:
#  test-app:
#    name: test-app
