version: "3.1"  # optional since v1.27.0
services:
  mongodb:
    image: mongo:4.4.13
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "27017:27017"
    restart: always
#    networks:
#      - test-app
#networks:
#  test-app:
#    name: test-app